create table "Order"
(
    id             int PRIMARY KEY generated by default as identity,
    order_date     DATE                         not null,
    order_status   varchar                      not null,
    payment_method varchar                      not null,
    customer_id    int references customer (id) not null
);

insert into "Order"(order_date, order_status, payment_method, customer_id)
VALUES ('12/04/2022', 'PROCESSING', 'CREDIT_CARD', 1);

insert into "Order"(order_date, order_status, payment_method, customer_id)
VALUES ('10/01/2023', 'SHIPPED', 'CREDIT_CARD', 1);

insert into "Order"(order_date, order_status, payment_method, customer_id)
VALUES ('06/07/2022', 'SHIPPED', 'ON_RECEIPT', 2);

insert into "Order"(order_date, order_status, payment_method, customer_id)
VALUES ('14/11/2022', 'SHIPPED', 'PAY_PAL', 3);

insert into "Order"(order_date, order_status, payment_method, customer_id)
VALUES ('10/01/2023', 'CANCELLED', 'CREDIT_CARD', 3);

insert into "Order"(order_date, order_status, payment_method, customer_id)
VALUES ('14/04/2023', 'CREATED', 'ON_RECEIPT', 3);


