create table Product
(
    id          int primary key generated BY DEFAULT as identity,
    name        varchar(100)            not null,
    price       int check ( price > 0 ) not null,
    description varchar                 not null,
    in_stock    bool                    not null
);

insert into product(name, price, description, in_stock)
VALUES ('tomato', 50, 'red and round', true);

insert into product(name, price, description, in_stock)
VALUES ('orange', 30, 'orange and round', true);

insert into product(name, price, description, in_stock)
VALUES ('bicycle', 10000, '2 wheels and so comfortable', false);

insert into product(name, price, description, in_stock)
VALUES ('sugar', 100, 'for tea', true);


